name: publish
on:
  push:
    tags:
      - "v*"
jobs:
  tests:
    uses: brickhouse-tech/.github/.github/workflows/tests.yml@main
    with:
      node-versions: '["18.x", "20.x", "22.x"]'
  publish:
    needs: [tests]
    uses: brickhouse-tech/.github/.github/workflows/publish.yml@main
