name: release
on:
  push:
    branches: ["master"]
    tags-ignore: ['**']
jobs:
  tests:
    uses: brickhouse-tech/.github/.github/workflows/tests.yml@main
    with:
      node-versions: '["20.x"]'
  release:
    needs: [tests]
    uses: brickhouse-tech/.github/.github/workflows/release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
